---
- hosts: tapir
  become_user: "{{pac}}-{{user}}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # see https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user
    ansible_common_remote_group: "{{pac}}"
    ansible_remote_tmp: ~/.ansible/tmp

  tasks:
  # see separate playbook-init.yml; we need postgresql extension unaccent and hstore
  #- name: Create user, domain and database
  #  import_tasks: tasks/hs_basis.yml

  #################################
  # check for postgresql extensions
  #################################
  - name: upload the password for the postgresql database
    become: yes
    template:
      src: "templates/pgpass"
      dest: "/home/pacs/{{pac}}/users/{{user}}/.pgpass"
      mode: "700"

  - name: check for unaccent
    become: yes
    shell: |
        export ext="unaccent"
        psql --user {{pac}}_{{user}} -c "SELECT * FROM pg_extension where extname = '$ext'" | grep "$ext" || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/"

  - name: check for hstore
    become: yes
    shell: |
        export ext="hstore"
        psql --user {{pac}}_{{user}} -c "SELECT * FROM pg_extension where extname = '$ext'" | grep "$ext" || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/"

  #################################
  ## create directories
  #################################
  - name: create directory etc
    become: yes
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/etc"
      state: directory
  - name: create directory var/tmp
    become: yes
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/var/tmp"
      state: directory
  - name: create directory var/log
    become: yes
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/var/log"
      state: directory
  - name: create directory var/run
    become: yes
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/var/run"
      state: directory

  #######################################################
  ## add configuration for monit and logrotate and redis
  #######################################################
  - name: upload monit configuration
    become: yes
    template: dest="/home/pacs/{{pac}}/users/{{user}}/.monitrc" src="templates/monitrc" mode=0600

  - name: upload logrotate configuration
    become: yes
    template: dest="/home/pacs/{{pac}}/users/{{user}}/.logrotate" src="templates/logrotate" mode=0600

  - name: upload redis configuration
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/etc/redis.conf" src="templates/redis.conf" mode=0600

  - name: upload celery worker start script
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/bin" src="templates/celery-worker-start.sh" mode=0700

  - name: upload celery worker stop script
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/bin" src="templates/celery-worker-stop.sh" mode=0700

  - name: upload celery beat start script
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/bin" src="templates/celery-beat-start.sh" mode=0700

  - name: upload celery beat stop script
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/bin" src="templates/celery-beat-stop.sh" mode=0700

  #################################
  ## install requirements
  #################################

  - name: Install slapd
    import_tasks: tasks/hs_slapd.yml

  - name: install poetry
    become: yes
    shell: |
      curl -sSL https://install.python-poetry.org | python3 - || exit -1
      echo 'export PATH="/home/pacs/{{pac}}/users/{{user}}/.local/bin:$PATH"' >> /home/pacs/{{pac}}/users/{{user}}/.profile
      chmod a+x /home/pacs/{{pac}}/users/{{user}}/.profile
      touch /home/pacs/{{pac}}/users/{{user}}/.ansible_poetry_installed
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}"
      creates: "/home/pacs/{{pac}}/users/{{user}}/.ansible_poetry_installed"

  # on Debian Buster, we only have Python 3.7; but poetry demands 3.10
  - name: install Python 3.10
    become: yes
    shell: |
      mkdir -p /home/pacs/{{pac}}/users/{{user}}/opt || exit -1
      mkdir -p /home/pacs/{{pac}}/users/{{user}}/build || exit -1
      cd /home/pacs/{{pac}}/users/{{user}}/build
      wget https://www.python.org/ftp/python/{{python_version}}/Python-{{python_version}}.tgz
      tar xzf Python-{{python_version}}.tgz
      cd Python-{{python_version}}
      ./configure --enable-optimizations --prefix=/home/pacs/{{pac}}/users/{{user}}/opt || exit -1
      make || exit -1
      make install || exit -1
      rm -rf /home/pacs/{{pac}}/users/{{user}}/build
      echo 'export PATH="/home/pacs/{{pac}}/users/{{user}}/opt/bin:$PATH"' >> /home/pacs/{{pac}}/users/{{user}}/.profile
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}"
      creates: "/home/pacs/{{pac}}/users/{{user}}/opt/bin/python3.10"

  ##################################
  ## install tapir
  ##################################

  - name: create directory tapir
    become: yes
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/tapir"
      state: directory

  - name: install tapir
    become: yes
    unarchive:
      src: https://github.com/SuperCoopBerlin/tapir/archive/refs/heads/master.tar.gz
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/tapir
      extra_opts: [--strip-components=1]
      creates: /home/pacs/{{pac}}/users/{{user}}/tapir/manage.py

  - name: create venv
    become: yes
    shell: |
      source /home/pacs/{{pac}}/users/{{user}}/.profile
      python3 -m venv .venv || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/tapir"
      creates: "/home/pacs/{{pac}}/users/{{user}}/tapir/.venv"

  - name: install poetry packages
    become: yes
    shell: |
      source .venv/bin/activate
      source /home/pacs/{{pac}}/users/{{user}}/.profile
      poetry install || exit -1
      touch /home/pacs/{{pac}}/users/{{user}}/.ansible_packages_installed
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/tapir"
      creates: "/home/pacs/{{pac}}/users/{{user}}/.ansible_packages_installed"

  ##################################
  ## configuration
  ##################################

  - name: upload configuration file
    become: yes
    template:
      src: "templates/settings.py"
      dest: "/home/pacs/{{pac}}/users/{{user}}/tapir/tapir/settings.py"

  - name: upload the password for the postgresql database
    become: yes
    template:
      src: "templates/pgpass"
      dest: "/home/pacs/{{pac}}/users/{{user}}/.pgpass"
      mode: "700"

  ######################
  ## initialise instance
  ######################

  - name: initialise instance
    become: yes
    shell: |
      source .venv/bin/activate
      source /home/pacs/{{pac}}/users/{{user}}/.profile
      poetry run python manage.py compilemessages --ignore ".venv" || exit -1
      poetry run python manage.py collectstatic --noinput --clear || exit -1
      poetry run python manage.py migrate || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/tapir"

  - name: load admin account
    become: yes
    shell: |
      source .venv/bin/activate
      source /home/pacs/{{pac}}/users/{{user}}/.profile
      poetry run python manage.py loaddata admin_account || exit -1
      touch /home/pacs/{{pac}}/users/{{user}}/.ansible_load_admin_account
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/tapir"
      creates: "/home/pacs/{{pac}}/users/{{user}}/.ansible_load_admin_account"

  - name: load ldap scheme
    become: yes
    shell: |
      ldapadd -x -h localhost:{{ldap_port}} -D "cn={{ldap_admin_username}},{{ldap_base_dn}}" -w "{{ldap_admin_password}}" -f ldap_testdata.ldif || exit -1
      touch /home/pacs/{{pac}}/users/{{user}}/.ansible_init_ldap_scheme
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/tapir"
      creates: "/home/pacs/{{pac}}/users/{{user}}/.ansible_init_ldap_scheme"

  - name: load sample data
    become: yes
    shell: |
      source .venv/bin/activate
      source /home/pacs/{{pac}}/users/{{user}}/.profile
      poetry run python manage.py generate_test_data --reset_all || exit -1
      touch /home/pacs/{{pac}}/users/{{user}}/.ansible_load_sample_data
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/tapir"
      creates: "/home/pacs/{{pac}}/users/{{user}}/.ansible_load_sample_data"

  # Debug mode was needed for loading the sample data
  - name: disable Debug mode
    become: yes
    replace:
      path: "/home/pacs/{{pac}}/users/{{user}}/tapir/tapir/settings.py"
      regexp: '^DEBUG = True$'
      replace: 'DEBUG = False'

  # TODO: missing the password in ldap?
  #- name: create super user
  #  become: yes
  #  shell: |
  #    source .venv/bin/activate
  #    source /home/pacs/{{pac}}/users/{{user}}/.profile
  #    echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(is_superuser=True).exists() or User.objects.create_superuser('{{admin_name}}', '{{admin_email}}', '{{admin_password}}')" | python manage.py shell || exit -1
  #    touch /home/pacs/{{pac}}/users/{{user}}/.ansible_init_admin
  #  args:
  #    executable: /bin/bash
  #    chdir: "/home/pacs/{{pac}}/users/{{user}}/tapir"
  #    creates: "/home/pacs/{{pac}}/users/{{user}}/.ansible_init_admin"

  ########################
  ## setup the apache site
  ########################

  - name: drop htaccess from htdocs-ssl
    become: yes
    file:
       path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl/.htaccess"
       state: absent
  - name: create symbolic link for static files
    become: yes
    file:
      src: "/home/pacs/{{pac}}/users/{{user}}/tapir/static"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl/static"
      state: link
  - name: upload passenger_wsgi.py file to app directory
    become: yes
    template: dest="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/app-ssl/passenger_wsgi.py" src="templates/passenger_wsgi.py" mode=0644
  - name: upload .htaccess file to domain directory
    become: yes
    template: dest="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/.htaccess" src="templates/domain_htaccess" mode=0644


  ####################################
  ## install cron jobs
  ####################################
  - name: start monit as cronjob
    become: yes
    cron:
      name: "start monit at reboot"
      special_time: reboot
      job: rm -f $HOME/var/run/* && /usr/bin/monit -c "$HOME/.monitrc"

  - name: run logrotate once a day
    become: yes
    cron:
      name: "logrotate"
      minute: "{{random_minute}}"
      hour: "1"
      job: "/usr/sbin/logrotate -s $HOME/.logrotate.state $HOME/.logrotate"

  ##############################################
  ## start services via monit
  ##############################################
  - name: start monit
    become: yes
    shell: |
      /usr/bin/monit -c ".monitrc"
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/"
      creates: "/home/pacs/{{pac}}/users/{{user}}/var/run/monit.id"
